_BASE_: ./base_unet.yaml

exp_name: apmcred_mri_lines=64_annealing

model:
  name: PMCRED
  forward_model:
    num_lines: 64
  score_fn:
    network_mode: sigma
    use_embed: True
  coeff:
    name: GeometricAnnealingCoeffModule
    decay_rate: 0.99
    min_sigma: 1.0e-2
  gamma: 5.0e-6
  alpha: 1.0e+4
  sigma: 348

inference:
  is_wandb_logger: False
  sample_args:
    tmax: 5000
    initialization: rand
  inference_args:
    max_num_batches: 1
    n_samples: 10

callbacks:
  scalarcallback:
    name: LocalScalarCallbackModule
    vis_freq: 1
  imagecallback:
    name: LocalGrayImageCallbackModule